[features]
resolution = true
skip-lint = false

[programs.devnet]
tot_token = "ToT1111111111111111111111111111111111111111"
transfer_hook = "Hook111111111111111111111111111111111111111"

[programs.mainnet-beta]
tot_token = "ToT1111111111111111111111111111111111111111"
transfer_hook = "Hook111111111111111111111111111111111111111"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts --reporter mochawesome --reporter-options reportDir=tests/reports/mochawesome,reportFilename=test-results,json=true,html=false"
test:report = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts --reporter mochawesome --reporter-options reportDir=tests/reports/mochawesome,reportFilename=test-results,json=true,html=false && npm run test:generate-report"

[test]
startup_wait = 10000

[workspace]
members = [
    "programs/tot-token",
    "programs/transfer-hook"
]
